/**
 * Manual Video List Configuration
 * Updated with user provided video list
 */

export const MANUAL_VIDEOS = [
    {
        id: 'video-13',
        title: '৪ বছরেই বাবারটা নেয় কথা বালার আগে চোদে',
        url: 'https://files.catbox.moe/9e2jtx.mp4',
        thumbnail: 'https://files.catbox.moe/1onxi5.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
        featured: true,
    },
    {
        id: 'video-2',
        title: 'বাবা নিজের ছোট মেয়ে কে কিভাবে করলো? ',
        url: 'https://files.catbox.moe/z93ga3.mp4',
        thumbnail: 'https://files.catbox.moe/e74861.png',
        category: 'Trending',
    },
    {
        id: 'video-5',
        title: 'চাচা খেয়ে দিল বাচ্চা মেয়ে কে',
        url: 'https://files.catbox.moe/iwobcf.mp4',
        thumbnail: 'https://files.catbox.moe/z642jx.png',
        category: 'Viral',
    },
    {
        id: 'video-4',
        title: 'কথাগুলো শুনুন',
        url: 'https://files.catbox.moe/se4ix7.mp4',
        thumbnail: 'https://files.catbox.moe/299jx7.png',
        category: 'Drama',
    },
    {
        id: 'video-1',
        title: 'আপন মা ছেলে',
        url: 'https://files.catbox.moe/czlssn.mp4',
        thumbnail: 'https://files.catbox.moe/3amsf4.png',
        category: 'New',
    },
    {
        id: 'video-6',
        title: 'Cousin ভাই বোন',
        url: 'https://files.catbox.moe/bas7fp.mp4',
        thumbnail: 'https://files.catbox.moe/gjq72f.png',
        category: 'Trending',
    },
    {
        id: 'video-7',
        title: 'আপন ছোট ভাই বোন',
        url: 'https://files.catbox.moe/nb9yfw.mp4',
        thumbnail: 'https://files.catbox.moe/ydi5st.png',
        category: 'New',
        featured: true,
    },
    {
        id: 'video-8',
        title: 'বউ আরাম খুজে ',
        url: 'https://files.catbox.moe/bwflxz.mp4',
        thumbnail: 'https://files.catbox.moe/dzv1um.png',
        category: 'Drama',
    },
    {
        id: 'video-9',
        title: '১০ বছরের ও কম মেয়ে কে করলো',
        url: 'https://files.catbox.moe/2zxgtw.mp4',
        thumbnail: 'https://files.catbox.moe/fzmchb.png',
        category: 'Viral',
        featured: true,
    },
    {
        id: 'video-10',
        title: 'মেয়ের দুধ হই নাই চোদা শিখেগিয়েছে',
        url: 'https://files.catbox.moe/0apck4.mp4',
        thumbnail: 'https://files.catbox.moe/i8sbns.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-3',
        title: 'আপন বাবা আর ছোট মেয়ে',
        url: 'https://files.catbox.moe/7sbi0e.mp4',
        thumbnail: 'https://files.catbox.moe/ppk2ki.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
        featured: true,
    },
    {
        id: 'video-11',
        title: 'বাবা ৭ বছরের মেয়েকে চুদে কাদিয়েও ছারেনি',
        url: 'https://files.catbox.moe/bw4ra0.mp4',
        thumbnail: 'https://files.catbox.moe/zfe2k4.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-12',
        title: 'ক্লাস ৮ এর মেয়ে কে গফ বানিয়ে করা',
        url: 'https://files.catbox.moe/dzqhhi.mp4',
        thumbnail: 'https://files.catbox.moe/7qa7jv.png',
        category: 'New',
    },
    {
        id: 'video-14',
        title: 'গফ বফ বাংলা কথা সহ',
        url: 'https://files.catbox.moe/4vo1cg.mp4',
        thumbnail: 'https://files.catbox.moe/njpawa.png',
        category: 'New',
    },
    {
        id: 'video-15',
        title: 'কেও নেই দাদি আছে',
        url: 'https://files.catbox.moe/ekzjgr.mp4',
        thumbnail: 'https://files.catbox.moe/cjuq4w.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-16',
        title: 'অনেক কষ্টে আম্মু রাজি হয়েছে',
        url: 'https://files.catbox.moe/4nway8.mp4',
        thumbnail: 'https://files.catbox.moe/wm6eq2.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-17',
        title: 'আম্মু আজকে বেশি হরনি হয়ে গেছে',
        url: 'https://files.catbox.moe/qc816y.mp4',
        thumbnail: 'https://files.catbox.moe/x3lytc.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-18',
        title: 'খালার সাহায্যে ছোট মেয়ে কে রেপ কথা সহ',
        url: 'https://files.catbox.moe/ohaju1.mp4',
        thumbnail: 'https://files.catbox.moe/voxckl.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-19',
        title: 'আপন ভাই বোন বাচ্চারা',
        url: 'https://files.catbox.moe/iwt1o3.mp4',
        thumbnail: 'https://files.catbox.moe/hsx76v.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-20',
        title: 'এমন cousin থাকলে আর কি লাগে?',
        url: 'https://files.catbox.moe/ogusxh.mp4',
        thumbnail: 'https://files.catbox.moe/l82sa3.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-21',
        title: 'বাবা নিজেই ৫ বছরের মেয়ে কে মাগি বানাচ্ছে কথা সহ',
        url: 'https://files.catbox.moe/b2g83c.mp4',
        thumbnail: 'https://files.catbox.moe/qlnr3d.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-22',
        title: '১০ এর বড় আপু দুধ টিপতে দেয়',
        url: 'https://files.catbox.moe/w37kkx.mp4',
        thumbnail: 'https://files.catbox.moe/8zqsfv.png',
        category: 'পারিবারিক',
        featured: true,
    },
    {
        id: 'video-23',
        title: 'দুধ ভাইরাল আপু',
        url: 'https://files.catbox.moe/fqqirr.mp4',
        thumbnail: 'https://files.catbox.moe/6e5h2b.png',
        category: 'পারিবারিক',
        featured: true,
    },
];

export const MANUAL_CONFIG = {
    ENABLED: true,  // Set to true to use this video list
    AUTO_THUMBNAIL: true,
};