/**
 * Manual Video List Configuration
 * Updated with user provided video list
 */

export const MANUAL_VIDEOS = [
    {
        id: 'dog-1',
        title: 'Dog and beautyful lady',
        url: 'https://files.catbox.moe/69s966.mp4',
        thumbnail: 'https://files.catbox.moe/eaxf2d.png',
        category: 'New',
    },
    {
        id: 'dog-2',
        title: 'Indian fucked dog',
        url: 'https://files.catbox.moe/xxywxu.mp4',
        thumbnail: 'https://files.catbox.moe/17b0y8.png',
        category: 'New',
    },
    {
        id: 'choto-1',
        title: 'Choto chele1',
        url: 'https://files.catbox.moe/pm9lqs.mp4',
        thumbnail: 'https://files.catbox.moe/h2bkyr.png',
        category: 'New',
    },
    {
        id: 'choto-2',
        title: 'Choto chele2',
        url: 'https://files.catbox.moe/fh717y.mp4',
        thumbnail: 'https://files.catbox.moe/evqzi3.png',
        category: 'New',
    },
    {
        id: 'choto-3',
        title: 'Choto chele3',
        url: 'https://files.catbox.moe/igmkvj.mp4',
        thumbnail: 'https://files.catbox.moe/ws31km.png',
        category: 'New',
    },
    {
        id: 'choto-4',
        title: 'Choto chele4',
        url: 'https://files.catbox.moe/7eatks.mp4',
        thumbnail: 'https://files.catbox.moe/3uwi0j.png',
        category: 'New',
    },
    {
        id: 'choto-5',
        title: 'Choto chele5',
        url: 'https://files.catbox.moe/xfslji.mp4',
        thumbnail: 'https://files.catbox.moe/tn7vaq.png',
        category: 'New',
    },
    {
        id: 'choto-6',
        title: 'Choto chele6',
        url: 'https://files.catbox.moe/3e88ka.mp4',
        thumbnail: 'https://files.catbox.moe/p4t4kj.png',
        category: 'New',
    },
    {
        id: 'choto-7',
        title: 'Choto chele7',
        url: 'https://files.catbox.moe/xu3f14.mp4',
        thumbnail: 'https://files.catbox.moe/ouwz2o.png',
        category: 'New',
    },
    {
        id: 'choto-8',
        title: 'Choto chele8',
        url: 'https://files.catbox.moe/iar2en.mp4',
        thumbnail: 'https://files.catbox.moe/y62bzl.png',
        category: 'New',
    },
    {
        id: 'choto-9',
        title: 'Choto chele9',
        url: 'https://files.catbox.moe/0macnp.mp4',
        thumbnail: 'https://files.catbox.moe/3yjtnj.png',
        category: 'New',
    },
    {
        id: 'choto-10',
        title: 'Choto chele10',
        url: 'https://files.catbox.moe/cfgi3z.mp4',
        thumbnail: 'https://files.catbox.moe/9m2b7r.png',
        category: 'New',
    },
    {
        id: 'new-1',
        title: '3 some gf rape',
        url: 'https://files.catbox.moe/ohpvdp.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-2',
        title: 'Aunt',
        url: 'https://files.catbox.moe/9301xo.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-3',
        title: 'বাব মেয়ে ৫ বছরের',
        url: 'https://files.catbox.moe/d59ra5.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-4',
        title: 'Deshi beauty',
        url: 'https://files.catbox.moe/br7htx.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-5',
        title: 'New Video 5',
        url: 'https://files.catbox.moe/ks5ggq.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-6',
        title: 'New Video 6',
        url: 'https://files.catbox.moe/qieksb.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-7',
        title: 'New Video 7',
        url: 'https://files.catbox.moe/gyqsxp.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-8',
        title: 'New Video 8',
        url: 'https://files.catbox.moe/8t87wj.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-9',
        title: 'New Video 9',
        url: 'https://files.catbox.moe/ejutl4.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-10',
        title: 'New Video 10',
        url: 'https://files.catbox.moe/42wkfm.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-11',
        title: 'New Video 11',
        url: 'https://files.catbox.moe/wabcn2.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-12',
        title: 'New Video 12',
        url: 'https://files.catbox.moe/aryfz7.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-13',
        title: 'New Video 13',
        url: 'https://files.catbox.moe/uuo7vf.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-14',
        title: 'New Video 14',
        url: 'https://files.catbox.moe/gj0rm7.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-15',
        title: 'New Video 15',
        url: 'https://files.catbox.moe/d9cmcp.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-16',
        title: 'New Video 16',
        url: 'https://files.catbox.moe/dd1g65.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-17',
        title: 'New Video 17',
        url: 'https://files.catbox.moe/e6sj0u.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-18',
        title: 'New Video 18',
        url: 'https://files.catbox.moe/5asdsb.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-19',
        title: 'New Video 19',
        url: 'https://files.catbox.moe/shxf19.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-20',
        title: 'New Video 20',
        url: 'https://files.catbox.moe/rpibx4.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-21',
        title: 'New Video 21',
        url: 'https://files.catbox.moe/za9r1w.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-22',
        title: 'New Video 22',
        url: 'https://files.catbox.moe/93ecpj.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-23',
        title: 'New Video 23',
        url: 'https://files.catbox.moe/jtdpq4.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-24',
        title: 'New Video 24',
        url: 'https://files.catbox.moe/q36m66.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-25',
        title: 'New Video 25',
        url: 'https://files.catbox.moe/hly85u.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-26',
        title: 'New Video 26',
        url: 'https://files.catbox.moe/um7bgz.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-27',
        title: 'New Video 27',
        url: 'https://files.catbox.moe/lvaso5.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-28',
        title: 'New Video 28',
        url: 'https://files.catbox.moe/m1cw6x.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-29',
        title: 'New Video 29',
        url: 'https://files.catbox.moe/08orwk.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-30',
        title: 'New Video 30',
        url: 'https://files.catbox.moe/cmwzt1.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-31',
        title: 'New Video 31',
        url: 'https://files.catbox.moe/v8otjo.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-32',
        title: 'New Video 32',
        url: 'https://files.catbox.moe/oc5vhd.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-33',
        title: 'New Video 33',
        url: 'https://files.catbox.moe/op9l63.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-34',
        title: 'New Video 34',
        url: 'https://files.catbox.moe/b0jnsr.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-35',
        title: 'New Video 35',
        url: 'https://files.catbox.moe/t585fe.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-36',
        title: 'New Video 36',
        url: 'https://files.catbox.moe/f49te3.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-37',
        title: 'New Video 37',
        url: 'https://files.catbox.moe/isu03b.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-38',
        title: 'New Video 38',
        url: 'https://files.catbox.moe/hqqu8l.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'new-39',
        title: 'New Video 39',
        url: 'https://files.catbox.moe/1xxv4i.mp4',
        thumbnail: '',
        category: 'New',
    },
    {
        id: 'video-13',
        title: '৪ বছরেই বাবারটা নেয় কথা বালার আগে চোদে',
        url: 'https://files.catbox.moe/9e2jtx.mp4',
        thumbnail: 'https://files.catbox.moe/1onxi5.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
        featured: true,
    },
    {
        id: 'video-2',
        title: 'বাবা নিজের ছোট মেয়ে কে কিভাবে করলো? ',
        url: 'https://files.catbox.moe/z93ga3.mp4',
        thumbnail: 'https://files.catbox.moe/e74861.png',
        category: 'Trending',
    },
    {
        id: 'video-5',
        title: 'চাচা খেয়ে দিল বাচ্চা মেয়ে কে',
        url: 'https://files.catbox.moe/iwobcf.mp4',
        thumbnail: 'https://files.catbox.moe/z642jx.png',
        category: 'Viral',
    },
    {
        id: 'video-4',
        title: 'কথাগুলো শুনুন',
        url: 'https://files.catbox.moe/se4ix7.mp4',
        thumbnail: 'https://files.catbox.moe/299jx7.png',
        category: 'Drama',
    },
    {
        id: 'video-1',
        title: 'আপন মা ছেলে',
        url: 'https://files.catbox.moe/czlssn.mp4',
        thumbnail: 'https://files.catbox.moe/3amsf4.png',
        category: 'New',
    },
    {
        id: 'video-6',
        title: 'Cousin ভাই বোন',
        url: 'https://files.catbox.moe/bas7fp.mp4',
        thumbnail: 'https://files.catbox.moe/gjq72f.png',
        category: 'Trending',
    },
    {
        id: 'video-7',
        title: 'আপন ছোট ভাই বোন',
        url: 'https://files.catbox.moe/nb9yfw.mp4',
        thumbnail: 'https://files.catbox.moe/ydi5st.png',
        category: 'New',
        featured: true,
    },
    {
        id: 'video-8',
        title: 'বউ আরাম খুজে ',
        url: 'https://files.catbox.moe/bwflxz.mp4',
        thumbnail: 'https://files.catbox.moe/dzv1um.png',
        category: 'Drama',
    },
    {
        id: 'video-9',
        title: '১০ বছরের ও কম মেয়ে কে করলো',
        url: 'https://files.catbox.moe/2zxgtw.mp4',
        thumbnail: 'https://files.catbox.moe/fzmchb.png',
        category: 'Viral',
        featured: true,
    },
    {
        id: 'video-10',
        title: 'মেয়ের দুধ হই নাই চোদা শিখেগিয়েছে',
        url: 'https://files.catbox.moe/0apck4.mp4',
        thumbnail: 'https://files.catbox.moe/i8sbns.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-3',
        title: 'আপন বাবা আর ছোট মেয়ে',
        url: 'https://files.catbox.moe/7sbi0e.mp4',
        thumbnail: 'https://files.catbox.moe/ppk2ki.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
        featured: true,
    },
    {
        id: 'video-11',
        title: 'বাবা ৭ বছরের মেয়েকে চুদে কাদিয়েও ছারেনি',
        url: 'https://files.catbox.moe/bw4ra0.mp4',
        thumbnail: 'https://files.catbox.moe/zfe2k4.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-12',
        title: 'ক্লাস ৮ এর মেয়ে কে গফ বানিয়ে করা',
        url: 'https://files.catbox.moe/dzqhhi.mp4',
        thumbnail: 'https://files.catbox.moe/7qa7jv.png',
        category: 'New',
    },
    {
        id: 'video-14',
        title: 'গফ বফ বাংলা কথা সহ',
        url: 'https://files.catbox.moe/4vo1cg.mp4',
        thumbnail: 'https://files.catbox.moe/njpawa.png',
        category: 'New',
    },
    {
        id: 'video-15',
        title: 'কেও নেই দাদি আছে',
        url: 'https://files.catbox.moe/ekzjgr.mp4',
        thumbnail: 'https://files.catbox.moe/cjuq4w.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-16',
        title: 'অনেক কষ্টে আম্মু রাজি হয়েছে',
        url: 'https://files.catbox.moe/4nway8.mp4',
        thumbnail: 'https://files.catbox.moe/wm6eq2.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-17',
        title: 'আম্মু আজকে বেশি হরনি হয়ে গেছে',
        url: 'https://files.catbox.moe/qc816y.mp4',
        thumbnail: 'https://files.catbox.moe/x3lytc.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-18',
        title: 'খালার সাহায্যে ছোট মেয়ে কে রেপ কথা সহ',
        url: 'https://files.catbox.moe/ohaju1.mp4',
        thumbnail: 'https://files.catbox.moe/voxckl.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-19',
        title: 'আপন ভাই বোন বাচ্চারা',
        url: 'https://files.catbox.moe/iwt1o3.mp4',
        thumbnail: 'https://files.catbox.moe/hsx76v.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-20',
        title: 'এমন cousin থাকলে আর কি লাগে?',
        url: 'https://files.catbox.moe/ogusxh.mp4',
        thumbnail: 'https://files.catbox.moe/l82sa3.png',
        category: 'পারিবারিক',
    },
    {
        id: 'video-21',
        title: 'বাবা নিজেই ৫ বছরের মেয়ে কে মাগি বানাচ্ছে কথা সহ',
        url: 'https://files.catbox.moe/b2g83c.mp4',
        thumbnail: 'https://files.catbox.moe/qlnr3d.png',
        category: ['পারিবারিক', 'বাচ্চাদের সেক্স'],
    },
    {
        id: 'video-22',
        title: '১০ এর বড় আপু দুধ টিপতে দেয়',
        url: 'https://files.catbox.moe/w37kkx.mp4',
        thumbnail: 'https://files.catbox.moe/8zqsfv.png',
        category: 'পারিবারিক',
        featured: true,
    },
    {
        id: 'video-23',
        title: 'দুধ ভাইরাল আপু',
        url: 'https://files.catbox.moe/fqqirr.mp4',
        thumbnail: 'https://files.catbox.moe/6e5h2b.png',
        category: 'পারিবারিক',
        featured: true,
    },
];

export const MANUAL_CONFIG = {
    ENABLED: true,  // Set to true to use this video list
    AUTO_THUMBNAIL: true,
};